In [2]:
# Importação de bibliotecas
import pandas as pd

In [51]:
# Lendo arquivos no excel
# df = Data Frame

df = pd.read_excel(r"Planilhas\DataBase_v1 (1).xlsx",
    sheet_name="EQUIPE",
    usecols=["SENIORIDADE", "DESCRICAO_AT", "AUSENCIA_TIPO"],
)

df.head()
df

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
0     Consultor          Pr           NaN
1     Consultor          Sr           NaN
2     Consultor          Ex        FÉRIAS
3     Consultor          Sr           NaN
4     Consultor          Jr           NaN
..          ...         ...           ...
60    Consultor          Pr           NaN
61    Consultor          Sr           NaN
62    Consultor          Sr           NaN
63    Consultor          Pr           NaN
64    Consultor          Ex        FÉRIAS

[65 rows x 3 columns]

In [37]:
# DFS disponíveis no ambiente
%whos DataFrame

Variable       Type         Data/Info
-------------------------------------
consultor_Jr   DataFrame    Shape: (0, 2)
df             DataFrame    Shape: (65, 2)

In [ ]:
#Verificando os tipos de senioridade
print(df["SENIORIDADE"].unique())

<StringArray>
['Pr', 'Sr', 'Ex', 'Jr', 'Bg']
Length: 5, dtype: str

In [53]:
# Filtrando os consultores do tipo Jr
consultor_Jr = df[df["SENIORIDADE"] == "Jr"]
consultor_Jr.head(100)

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
4     Consultor          Jr           NaN
5     Consultor          Jr           NaN
7     Consultor          Jr           NaN
11    Consultor          Jr           NaN
15    Consultor          Jr           NaN
16    Consultor          Jr           NaN
34    Consultor          Jr           NaN
37    Consultor          Jr           NaN
39    Consultor          Jr           NaN
45    Consultor          Jr           NaN

In [84]:
# Filtrando os consultores que estão ausentes por férias
consultores_Ausentes = df[df["AUSENCIA_TIPO"] == "FÉRIAS"]
consultores_Ausentes.head(60)

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
2     Consultor          Ex        FÉRIAS
13    Consultor          Sr        FÉRIAS
22    Consultor          Pr        FÉRIAS
25    Consultor          Sr        FÉRIAS
49    Consultor          Sr        FÉRIAS
51    Consultor          Ex        FÉRIAS
64    Consultor          Ex        FÉRIAS

In [85]:
# Verificando quais colunas existem no DataFrame
print(consultores_Ausentes.columns.tolist())

['DESCRICAO_AT', 'SENIORIDADE', 'AUSENCIA_TIPO']

In [82]:
# Filtrando somente os consultores do tipo Jr que estão ausentes por férias
consultores_Ausentes_Jr = df[(df["SENIORIDADE"] == "Jr") & (df["AUSENCIA_TIPO"] == "FÉRIAS")]
consultores_Ausentes_Jr.head(60)

Empty DataFrame
Columns: [DESCRICAO_AT, SENIORIDADE, AUSENCIA_TIPO]
Index: []

In [90]:
# Contagem de quantos consultores do tipo Jr estão ausentes por férias
consultores_Ausentes_Jr.count()

DESCRICAO_AT     0
SENIORIDADE      0
AUSENCIA_TIPO    0
dtype: int64

In [ ]:
# Filtrando consultores do tipo Sr  estão ausentes por férias
consultores_Ausentes_Sr = df[(df["SENIORIDADE"] == "Sr") & (df["AUSENCIA_TIPO"] == "FÉRIAS")]
consultores_Ausentes_Sr.head(100)

ValueError: No axis named 100 for object type DataFrame

In [92]:
# Contagem de quantos consultores do tipo Sr estão ausentes por férias
consultores_Ausentes_Sr.count()

DESCRICAO_AT     3
SENIORIDADE      3
AUSENCIA_TIPO    3
dtype: int64

In [96]:
# Fazendo percentual relativo 
# Use len() para contar linhas corretamente
percentual_representativo = (len(consultores_Ausentes) / len(consultores_Ausentes_Sr)) * 100
print(f"{percentual_representativo:.2f}%")

233.33%